# Generated by Django 3.1 on 2020-08-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sound_Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_title', models.CharField(max_length=200)),
                ('audio_timestamp', models.DateTimeField(auto_now=True)),
                ('audio_upload', models.FileField(null=True, upload_to='audio/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Sound_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=200)),
                ('video_timestamp', models.DateTimeField(auto_now=True)),
                ('video_upload', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
    ]
